# Generated by Django 5.0.6 on 2024-07-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_role_remove_customuser_user_type_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='telegram_username',
            new_name='country',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
