# Generated by Django 5.0.6 on 2024-07-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('repeatTime', models.CharField(max_length=255)),
                ('selectIconIndex', models.IntegerField(default=0)),
                ('addNote', models.CharField(max_length=255, null=True)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('endDate', models.DateField(auto_now=True)),
                ('startTime', models.TimeField(auto_now_add=True)),
                ('endTime', models.TimeField(auto_now=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_income', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('datetime', models.DateTimeField(auto_created=True)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('priority', models.CharField(default=0, max_length=255)),
                ('icon_color', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('geoPoint', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
