# Generated by Django 5.0.6 on 2024-07-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
